sudo: true
language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-8
          - g++-8
script:
  - export CXX=g++-8
  - export CC=gcc-8
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt510base qt510multimedia qt510translations qt510tools
  - source /opt/qt510/bin/qt510-env.sh 
  - export QTHOME=/opt/qt510
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j20
